// Generated by Supabase MCP — do not edit by hand.
// Regenerate after every migration via:
//   mcp__supabase__generate_typescript_types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      activities: {
        Row: {
          age_max: number | null
          age_min: number | null
          badges: string[] | null
          bucket: string
          cleanup: string | null
          completed_at: string | null
          completed_source: string | null
          created_at: string
          day: string
          duration_min: number
          execution_steps: Json | null
          family_id: string
          id: string
          inspiration_detail: string | null
          inspiration_source: string | null
          kid_ids: string[]
          materials: Json | null
          methodology: string | null
          prep_time_min: number | null
          reasoning: string | null
          safety_notes: string | null
          scheduled_reminder_at: string | null
          setup: string | null
          signs_it_worked: string | null
          skills_developed: string[] | null
          start_hour: number
          status: string
          summary: string | null
          title: string
          troubleshooting: string | null
          updated_at: string
          variations: Json | null
          weather_snapshot: Json | null
          weather_suitable: string[] | null
          week_plan_id: string
        }
        Insert: {
          age_max?: number | null
          age_min?: number | null
          badges?: string[] | null
          bucket: string
          cleanup?: string | null
          completed_at?: string | null
          completed_source?: string | null
          created_at?: string
          day: string
          duration_min: number
          execution_steps?: Json | null
          family_id: string
          id?: string
          inspiration_detail?: string | null
          inspiration_source?: string | null
          kid_ids?: string[]
          materials?: Json | null
          methodology?: string | null
          prep_time_min?: number | null
          reasoning?: string | null
          safety_notes?: string | null
          scheduled_reminder_at?: string | null
          setup?: string | null
          signs_it_worked?: string | null
          skills_developed?: string[] | null
          start_hour: number
          status?: string
          summary?: string | null
          title: string
          troubleshooting?: string | null
          updated_at?: string
          variations?: Json | null
          weather_snapshot?: Json | null
          weather_suitable?: string[] | null
          week_plan_id: string
        }
        Update: {
          age_max?: number | null
          age_min?: number | null
          badges?: string[] | null
          bucket?: string
          cleanup?: string | null
          completed_at?: string | null
          completed_source?: string | null
          created_at?: string
          day?: string
          duration_min?: number
          execution_steps?: Json | null
          family_id?: string
          id?: string
          inspiration_detail?: string | null
          inspiration_source?: string | null
          kid_ids?: string[]
          materials?: Json | null
          methodology?: string | null
          prep_time_min?: number | null
          reasoning?: string | null
          safety_notes?: string | null
          scheduled_reminder_at?: string | null
          setup?: string | null
          signs_it_worked?: string | null
          skills_developed?: string[] | null
          start_hour?: number
          status?: string
          summary?: string | null
          title?: string
          troubleshooting?: string | null
          updated_at?: string
          variations?: Json | null
          weather_snapshot?: Json | null
          weather_suitable?: string[] | null
          week_plan_id?: string
        }
        Relationships: []
      }
      families: {
        Row: {
          agent_level: string
          city: string | null
          created_at: string
          density: string
          household_name: string
          id: string
          locale: string
          methodologies: string[]
          timezone: string
          updated_at: string
        }
        Insert: {
          agent_level?: string
          city?: string | null
          created_at?: string
          density?: string
          household_name: string
          id?: string
          locale?: string
          methodologies?: string[]
          timezone?: string
          updated_at?: string
        }
        Update: {
          agent_level?: string
          city?: string | null
          created_at?: string
          density?: string
          household_name?: string
          id?: string
          locale?: string
          methodologies?: string[]
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      family_invitations: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          avatar_color: string
          created_at: string
          email: string
          expires_at: string
          family_id: string
          id: string
          invited_by: string
          role: string
          status: string
          token: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          avatar_color?: string
          created_at?: string
          email: string
          expires_at?: string
          family_id: string
          id?: string
          invited_by: string
          role?: string
          status?: string
          token: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          avatar_color?: string
          created_at?: string
          email?: string
          expires_at?: string
          family_id?: string
          id?: string
          invited_by?: string
          role?: string
          status?: string
          token?: string
        }
        Relationships: []
      }
      family_members: {
        Row: {
          auth_user_id: string
          avatar_color: string
          created_at: string
          family_id: string
          id: string
          is_owner: boolean
          name: string
          role: string
        }
        Insert: {
          auth_user_id: string
          avatar_color?: string
          created_at?: string
          family_id: string
          id?: string
          is_owner?: boolean
          name: string
          role?: string
        }
        Update: {
          auth_user_id?: string
          avatar_color?: string
          created_at?: string
          family_id?: string
          id?: string
          is_owner?: boolean
          name?: string
          role?: string
        }
        Relationships: []
      }
      family_preferences: {
        Row: {
          created_at: string
          family_id: string
          id: string
          kind: string
          text: string
        }
        Insert: {
          created_at?: string
          family_id: string
          id?: string
          kind: string
          text: string
        }
        Update: {
          created_at?: string
          family_id?: string
          id?: string
          kind?: string
          text?: string
        }
        Relationships: []
      }
      kids: {
        Row: {
          age: number
          avatar_color: string
          color: string
          created_at: string
          family_id: string
          id: string
          name: string
          tags: string[]
          updated_at: string
        }
        Insert: {
          age: number
          avatar_color?: string
          color?: string
          created_at?: string
          family_id: string
          id?: string
          name: string
          tags?: string[]
          updated_at?: string
        }
        Update: {
          age?: number
          avatar_color?: string
          color?: string
          created_at?: string
          family_id?: string
          id?: string
          name?: string
          tags?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      llm_calls: {
        Row: {
          cost_usd: number
          created_at: string
          family_id: string | null
          id: string
          model: string
          purpose: string
          tokens_in: number
          tokens_out: number
        }
        Insert: {
          cost_usd?: number
          created_at?: string
          family_id?: string | null
          id?: string
          model: string
          purpose: string
          tokens_in?: number
          tokens_out?: number
        }
        Update: {
          cost_usd?: number
          created_at?: string
          family_id?: string | null
          id?: string
          model?: string
          purpose?: string
          tokens_in?: number
          tokens_out?: number
        }
        Relationships: []
      }
      personal_activities: {
        Row: {
          active_from: string | null
          active_until: string | null
          category: string
          color: string
          created_at: string
          day: string | null
          duration_min: number
          family_id: string
          family_member_id: string | null
          id: string
          is_recurring: boolean
          notes: string | null
          recurring_days: string[]
          start_hour: number
          title: string
          updated_at: string
          week_start_date: string | null
        }
        Insert: {
          active_from?: string | null
          active_until?: string | null
          category: string
          color?: string
          created_at?: string
          day?: string | null
          duration_min: number
          family_id: string
          family_member_id?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          recurring_days?: string[]
          start_hour: number
          title: string
          updated_at?: string
          week_start_date?: string | null
        }
        Update: {
          active_from?: string | null
          active_until?: string | null
          category?: string
          color?: string
          created_at?: string
          day?: string | null
          duration_min?: number
          family_id?: string
          family_member_id?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          recurring_days?: string[]
          start_hour?: number
          title?: string
          updated_at?: string
          week_start_date?: string | null
        }
        Relationships: []
      }
      week_plans: {
        Row: {
          family_id: string
          generated_at: string
          id: string
          status: string
          weather_forecast: Json | null
          week_start_date: string
        }
        Insert: {
          family_id: string
          generated_at?: string
          id?: string
          status?: string
          weather_forecast?: Json | null
          week_start_date: string
        }
        Update: {
          family_id?: string
          generated_at?: string
          id?: string
          status?: string
          weather_forecast?: Json | null
          week_start_date?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_family_invitation: { Args: { p_token: string }; Returns: string }
      create_family_for_current_user: {
        Args: {
          p_city: string
          p_household_name: string
          p_locale: string
          p_member_avatar_color: string
          p_member_name: string
          p_member_role: string
          p_timezone: string
        }
        Returns: string
      }
      create_family_invitation: {
        Args: { p_avatar_color: string; p_email: string; p_role: string }
        Returns: string
      }
      current_family_id: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<T extends keyof DefaultSchema['Tables']> = DefaultSchema['Tables'][T]['Row']

export type TablesInsert<T extends keyof DefaultSchema['Tables']> =
  DefaultSchema['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof DefaultSchema['Tables']> =
  DefaultSchema['Tables'][T]['Update']
