// Category taxonomy ported from reference/engine.js with English display
// strings replaced by stable keys. Display names live in messages/*.json under
// `finance.categories.*` / `finance.segments.*` (next-intl).

import type { CategoryKey, CategoryRule, Segment } from './types'

// Reference-order rule list. DO NOT reorder: first match wins, and several
// pairs are deliberately sequenced ('uber eats' before 'uber', 'apple.com'
// before 'apple', 'central park'/'parks broward' before 'parking'/'parkin').
// This constant exists only as seed data for `finance_category_rules` and for
// tests — the engine itself always takes rules as a parameter.
export const DEFAULT_RULES: CategoryRule[] = [
  // Exact-merchant rule: the reference special-cases merchant === 'UPS' ahead
  // of all substring rules ('ups' as a substring would over-match).
  { match: 'ups', category: 'business_software', exact: true },
  { match: 'apmex', category: 'investments' },
  { match: 'peacock', category: 'subscriptions' },
  { match: 'tesla', category: 'transportation_auto' },
  { match: 'speedway', category: 'transportation_auto' },
  { match: 'service plaza', category: 'transportation_auto' },
  { match: 'seed to table', category: 'groceries_household' },
  { match: 'brooks burgers', category: 'dining_takeout' },
  { match: 'crust pizza', category: 'dining_takeout' },
  { match: 'pizza', category: 'dining_takeout' },
  { match: 'burger', category: 'dining_takeout' },
  { match: 'airbnb', category: 'travel' },
  { match: 'hotel', category: 'travel' },
  { match: 'american airlines', category: 'travel' },
  { match: 'airlines', category: 'travel' },
  { match: 'marriott', category: 'travel' },
  { match: 'whole foods', category: 'groceries_household' },
  { match: 'uber eats', category: 'dining_takeout' },
  { match: 'ubereats', category: 'dining_takeout' },
  { match: 'lyft', category: 'transportation_auto' },
  { match: 'uber', category: 'transportation_auto' },
  { match: 'tax collector', category: 'taxes_fees' },
  { match: "lily's mediterranean", category: 'dining_takeout' },
  { match: 'lilys medi', category: 'dining_takeout' },
  { match: '365 retail markets', category: 'dining_takeout' },
  { match: 'entertain st', category: 'entertainment_recreation' },
  { match: 's.fl.ent', category: 'entertainment_recreation' },
  { match: 'verizon', category: 'phone' },
  { match: 'costa del sol', category: 'hoa' },
  { match: 'bark square', category: 'pets' },
  { match: 'petco', category: 'pets' },
  { match: 'petsmart', category: 'pets' },
  { match: 'chewy', category: 'pets' },
  { match: 'n8n', category: 'business_software' },
  { match: 'etsy', category: 'shopping_retail' },
  { match: 'ebay', category: 'shopping_retail' },
  { match: 'groupon', category: 'shopping_retail' },
  { match: 'tellmytale', category: 'shopping_retail' },
  { match: 'panda express', category: 'dining_takeout' },
  { match: 'mister 01', category: 'dining_takeout' },
  { match: 'michi', category: 'dining_takeout' },
  { match: 'pauloluigi', category: 'dining_takeout' },
  { match: 'daily bread', category: 'dining_takeout' },
  { match: 'cucu place', category: 'dining_takeout' },
  { match: 'juice bar', category: 'dining_takeout' },
  { match: 'bluehost', category: 'business_software' },
  { match: 'replit', category: 'business_software' },
  { match: 'supabase', category: 'business_software' },
  { match: 'openai', category: 'business_software' },
  { match: 'elevenlabs', category: 'business_software' },
  { match: 'moonshot', category: 'business_software' },
  { match: 'twilio', category: 'business_software' },
  { match: 'wispr', category: 'business_software' },
  { match: 'prodigi', category: 'business_software' },
  { match: 'google cloud', category: 'business_software' },
  { match: 'facebk', category: 'business_software' },
  { match: 'facebook', category: 'business_software' },
  { match: 'division of corporations', category: 'business_software' },
  { match: 'polsia', category: 'business_software' },
  { match: 'fabuloom', category: 'business_software' },
  { match: 'xai', category: 'business_software' },
  { match: 'spotify', category: 'subscriptions' },
  { match: 'apple.com', category: 'subscriptions' },
  { match: 'apple', category: 'subscriptions' },
  { match: 'state farm', category: 'insurance' },
  { match: 'insurance', category: 'insurance' },
  { match: 'cvs', category: 'health_medical' },
  { match: 'walgreens', category: 'health_medical' },
  { match: 'pharmacy', category: 'health_medical' },
  { match: 'dental', category: 'health_medical' },
  { match: 'glassesusa', category: 'health_medical' },
  { match: 'for eyes', category: 'health_medical' },
  { match: 'beauty bar', category: 'personal_care_beauty' },
  { match: 'nimi skincare', category: 'personal_care_beauty' },
  { match: 'skincare', category: 'personal_care_beauty' },
  { match: 'central park', category: 'entertainment_recreation' },
  { match: 'museum', category: 'entertainment_recreation' },
  { match: 'kidstrong', category: 'entertainment_recreation' },
  { match: 'parks broward', category: 'entertainment_recreation' },
  { match: 'shell', category: 'transportation_auto' },
  { match: 'car wash', category: 'transportation_auto' },
  { match: 'park one', category: 'transportation_auto' },
  { match: 'laz parking', category: 'transportation_auto' },
  { match: 'parking', category: 'transportation_auto' },
  { match: 'parkin', category: 'transportation_auto' },
  { match: 'auto tag', category: 'transportation_auto' },
  { match: 'walmart', category: 'groceries_household' },
  { match: 'winn-dixie', category: 'groceries_household' },
  { match: 'winn dixie', category: 'groceries_household' },
  { match: 'publix', category: 'groceries_household' },
  { match: 'thrive market', category: 'groceries_household' },
  { match: 'grazianos', category: 'groceries_household' },
  { match: 'meat club', category: 'groceries_household' },
  { match: 'costco', category: 'groceries_household' },
  { match: 'home depot', category: 'housing_home' },
  { match: "lowe's", category: 'housing_home' },
  { match: 'ikea', category: 'housing_home' },
  { match: 'amazon', category: 'shopping_retail' },
  { match: 'target', category: 'shopping_retail' },
  { match: 'burlington', category: 'shopping_retail' },
  { match: "dick's", category: 'shopping_retail' },
  { match: 'dicks sporting', category: 'shopping_retail' },
  { match: 'tiktok', category: 'shopping_retail' },
  { match: 'gift shop', category: 'shopping_retail' },
  { match: 'piccola', category: 'dining_takeout' },
  { match: 'chick-fil', category: 'dining_takeout' },
  { match: 'cuban', category: 'dining_takeout' },
  { match: 'lasvegascuban', category: 'dining_takeout' },
  { match: 'five guys', category: 'dining_takeout' },
  { match: 'jimmy john', category: 'dining_takeout' },
  { match: 'chipotle', category: 'dining_takeout' },
  { match: 'papa john', category: 'dining_takeout' },
  { match: 'mcdonald', category: 'dining_takeout' },
  { match: 'pollo tropical', category: 'dining_takeout' },
  { match: 'wendy', category: 'dining_takeout' },
  { match: 'domino', category: 'dining_takeout' },
  { match: 'panera', category: 'dining_takeout' },
  { match: 'subway', category: 'dining_takeout' },
  { match: 'ceviche', category: 'dining_takeout' },
  { match: 'limon', category: 'dining_takeout' },
  { match: 'nahuen', category: 'dining_takeout' },
  { match: 'lebanese', category: 'dining_takeout' },
  { match: 'kabob', category: 'dining_takeout' },
  { match: 'sazon', category: 'dining_takeout' },
  { match: 'sazón', category: 'dining_takeout' },
  { match: 'milanezza', category: 'dining_takeout' },
  { match: 'boulangerie', category: 'dining_takeout' },
  { match: 'taco rico', category: 'dining_takeout' },
  { match: 'crema gourmet', category: 'dining_takeout' },
  { match: 'habit', category: 'dining_takeout' },
  { match: 'coal fired', category: 'dining_takeout' },
  { match: 'pummarola', category: 'dining_takeout' },
  { match: 'capriccio', category: 'dining_takeout' },
  { match: 'babilonia', category: 'dining_takeout' },
  { match: 'sabores', category: 'dining_takeout' },
  { match: 'confucio', category: 'dining_takeout' },
  { match: 'spruce juice', category: 'dining_takeout' },
  { match: 'rinconcito', category: 'dining_takeout' },
  { match: 'sproutz', category: 'dining_takeout' },
  { match: 'wawa', category: 'dining_takeout' },
  { match: 'doordash', category: 'dining_takeout' },
  { match: 'pizzeria', category: 'dining_takeout' },
  { match: 'restaurant', category: 'dining_takeout' },
  { match: 'espresso', category: 'dining_takeout' }
]

export const SEGMENT_OF: Record<CategoryKey, Segment> = {
  groceries_household: 'essential',
  health_medical: 'essential',
  insurance: 'essential',
  housing_home: 'essential',
  transportation_auto: 'essential',
  dining_takeout: 'lifestyle',
  shopping_retail: 'lifestyle',
  personal_care_beauty: 'lifestyle',
  entertainment_recreation: 'lifestyle',
  subscriptions: 'lifestyle',
  business_software: 'business',
  investments: 'investment',
  mortgage: 'essential',
  hoa: 'essential',
  utilities: 'essential',
  auto_loan: 'essential',
  student_loan: 'essential',
  kids_activities: 'lifestyle',
  phone: 'essential',
  travel: 'lifestyle',
  pets: 'lifestyle',
  taxes_fees: 'essential',
  uncategorized: 'unassigned',
  credits_rewards: 'adjustments',
  card_payment: 'adjustments'
}

// Fixed categories never flag as overspending — you can't overspend your
// mortgage.
export const FIXED_CATS: ReadonlySet<CategoryKey> = new Set([
  'mortgage',
  'hoa',
  'utilities',
  'auto_loan',
  'student_loan',
  'kids_activities',
  'phone'
])

// Lumpy categories are held flat in projections, not annualized — otherwise a
// single $5,435 bullion buy projects to $65k/yr.
export const LUMPY_CATS: ReadonlySet<CategoryKey> = new Set(['investments'])

export const CATEGORY_ORDER: CategoryKey[] = [
  'dining_takeout',
  'groceries_household',
  'shopping_retail',
  'business_software',
  'investments',
  'insurance',
  'personal_care_beauty',
  'health_medical',
  'entertainment_recreation',
  'transportation_auto',
  'subscriptions',
  'travel',
  'pets',
  'taxes_fees',
  'housing_home',
  'mortgage',
  'hoa',
  'utilities',
  'phone',
  'auto_loan',
  'student_loan',
  'kids_activities',
  'uncategorized'
]

export const SEGMENT_ORDER: Segment[] = [
  'essential',
  'lifestyle',
  'business',
  'investment',
  'unassigned'
]

export const CAT_COLORS: Record<CategoryKey, string> = {
  dining_takeout: '#B2473B',
  groceries_household: '#1F6F54',
  shopping_retail: '#C58A2E',
  business_software: '#3B5BA5',
  investments: '#6A4C93',
  insurance: '#4E7689',
  personal_care_beauty: '#C16B86',
  health_medical: '#2E8B8B',
  entertainment_recreation: '#D08A3E',
  transportation_auto: '#7A8450',
  subscriptions: '#8C6D4F',
  housing_home: '#5B7C99',
  travel: '#B5654D',
  pets: '#5F9EA0',
  taxes_fees: '#8A8574',
  mortgage: '#2F4B6E',
  hoa: '#6E8CA8',
  utilities: '#9C7A2E',
  auto_loan: '#46756B',
  student_loan: '#585A8C',
  kids_activities: '#CC7A52',
  phone: '#7C9BAA',
  uncategorized: '#9A9384',
  credits_rewards: '#B0A98F',
  card_payment: '#C9C2B0'
}

export const SEG_COLORS: Record<Segment, string> = {
  essential: '#1F6F54',
  lifestyle: '#B2473B',
  business: '#3B5BA5',
  investment: '#6A4C93',
  unassigned: '#9A9384',
  adjustments: '#C9C2B0'
}

// The reference implementation (and the handoff fixtures: config.json,
// golden-master.json) identify categories by their English display names.
// This map converts those names to stable keys — used by the seed script and
// the golden-master tests, never by runtime logic.
export const KEY_BY_REFERENCE_NAME: Record<string, CategoryKey> = {
  'Dining & Takeout': 'dining_takeout',
  'Groceries & Household': 'groceries_household',
  'Shopping & Retail': 'shopping_retail',
  'Business & Software': 'business_software',
  Investments: 'investments',
  Insurance: 'insurance',
  'Personal Care & Beauty': 'personal_care_beauty',
  'Health & Medical': 'health_medical',
  'Entertainment & Recreation': 'entertainment_recreation',
  'Transportation & Auto': 'transportation_auto',
  Subscriptions: 'subscriptions',
  Travel: 'travel',
  Pets: 'pets',
  'Taxes & Fees': 'taxes_fees',
  'Housing & Home': 'housing_home',
  Mortgage: 'mortgage',
  HOA: 'hoa',
  Utilities: 'utilities',
  Phone: 'phone',
  'Auto Loan': 'auto_loan',
  'Student Loan': 'student_loan',
  'Kids & Activities': 'kids_activities',
  Uncategorized: 'uncategorized',
  'Credits & Rewards': 'credits_rewards',
  'Card Payment': 'card_payment'
}
